GET http://localhost:8080/Tomcat/users/
Accept: */*
Cache-Control: no-cache

<> 2018-12-28T050733.200.json
<> 2018-12-28T050640.200.json
<> 2018-12-28T050358.200.json
###

GET http://localhost:8080/Tomcat/users/askor
Accept: */*
Cache-Control: no-cache

<> 2018-12-28T050735.200.json
<> 2018-12-28T050642.200.json
###


POST http://localhost:8080/Tomcat/users/
Accept: */*
Cache-Control: no-cache

{"username": "u1",
   "login": "u1",
      "password": "u1",
         "email": "u1@u1.org"}

<> 2018-12-28T050739.200.json
<> 2018-12-28T050645.500.html
###

PUT http://localhost:8080/Tomcat/users/u1
Accept: */*
Cache-Control: no-cache

{"username": "u1",
   "login": "u2",
      "password": "u2",
         "email": "u2@u2.org"}

<> 2018-12-28T050742.200.json

###

DELETE http://localhost:8080/Tomcat/users/u1
Accept: */*
Cache-Control: no-cache

{"username": "u1",
   "login": "u2",
      "password": "u2",
         "email": "u2@u2.org"}

<> 2018-12-28T050751.200.html
<> 2018-12-28T050744.404.html

###