GET http://localhost:8080/Tomcat1/users/
Accept: */*
Cache-Control: no-cache

<> 2018-12-28T050733.200.json
<> 2018-12-28T050640.200.json
<> 2018-12-28T050358.200.json
###

GET http://localhost:8080/Tomcat1-1.0-SNAPSHOT/users/
Content-Type: text/html
Accept: application/json
Cache-Control: no-cache

<> 2018-12-28T050733.200.json
<> 2018-12-28T050640.200.json
<> 2018-12-28T050358.200.json
###


GET http://localhost:8080/Tomcat1-1.0-SNAPSHOT/users/sscm75
Content-Type: text/html
Accept: application/json
Cache-Control: no-cache

<> 2018-12-28T050733.200.json
<> 2018-12-28T050640.200.json
<> 2018-12-28T050358.200.json
###

GET http://localhost:8080/Tomcat1/users/askor
Accept: */*
Cache-Control: no-cache

<> 2018-12-28T050735.200.json
<> 2018-12-28T050642.200.json
###


POST http://localhost:8080/Tomcat1/users/
Accept: */*
Cache-Control: no-cache

{"username": null, "login": null, "password": "uy", "email": "uy118@u18.org8"}

<> 2018-12-28T050739.200.json
<> 2018-12-28T050645.500.html
###

POST http://localhost:8080/Tomcat1-1.0-SNAPSHOT/users
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache
Accept-Datetime:

{"username": "4m8", "login": "4m67", "password": "4m7", "email": "s65@g"}

<> 2018-12-28T050739.200.json
<> 2018-12-28T050645.500.html
###

POST http://localhost:8080/Tomcat1-1.0-SNAPSHOT/users
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache
Accept-Datetime:

{"username": "asdf", "userman": "7t1r113", "login": "c48", "password": "r1114", "email": "41@1"}

<> 2018-12-28T050739.200.json
<> 2018-12-28T050645.500.html
###

PUT http://localhost:8080/Tomcat1/users/u1
Accept: */*
Cache-Control: no-cache

{
  "id": "2",
  "username": "2usdf",
  "login": "c1m",
  "password": "2u20",
  "email": "2ua@u20.org"
}


<> 2018-12-28T050742.200.json

###

PUT http://localhost:8080/Tomcat1-1.0-SNAPSHOT/users
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache

{
  "idshka": "7",
  "username": "2u16sdf",
  "login": "c1m",
  "password": "2au20",
  "email": "2ua02@u20.org"
}


<> 2018-12-28T050742.200.json

###


PUT http://localhost:8080/Tomcat1-1.0-SNAPSHOT/users
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache

{
  "id": "2",
  "username": null,
  "login": null,
  "password": null,
  "email": null
}

<> 2018-12-28T050742.200.json

###

PUT http://localhost:8080/Tomcat1-1.0-SNAPSHOT/users
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache

{
  "id": "4",
  "username": "askor",
  "login": "4525254",
  "password": "qsw345345ertw43",
  "email": "qsdf453453411w4"
}

<> 2018-12-28T050742.200.json

###

DELETE http://localhost:8080/Tomcat1-1.0-SNAPSHOT/users/
Content-Type: text/html
Accept: application/json
Cache-Control: no-cache

###

DELETE http://localhost:8080/Tomcat1/users/u1
Accept: */*
Cache-Control: no-cache

###

DELETE http://localhost:8080/Tomcat1-1.0-SNAPSHOT/users/778885
Content-Type: text/html
Accept: application/json
Cache-Control: no-cache

{
  "username": "u1",
  "login": "u2",
  "password": "u2",
  "email": "u2@u2.org"
}

<> 2018-12-28T050751.200.html
<> 2018-12-28T050744.404.html

###